# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0002_auto_20171001_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elasticsearchapp.Blog'),
        ),
    ]
