# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 04:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchapp', '0003_auto_20171001_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
